# syntax=docker/dockerfile:1

FROM node:20-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM node:20-slim AS builder
WORKDIR /app

# クライアント側環境変数（NEXT_PUBLIC_*）
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID

# サーバー側環境変数（ビルド時に必要）
ARG GCP_PROJECT_ID
ARG GCP_LOCATION
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_DATABASE_ID
ARG GCS_MANGA_BUCKET
ARG GCS_SIGNED_URL_TTL_MINUTES
ARG CLOUD_TASKS_QUEUE
ARG CLOUD_TASKS_LOCATION
ARG CLOUD_RUN_SERVICE_ACCOUNT
ARG MANGA_WORKER_URL

ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV GCP_PROJECT_ID=$GCP_PROJECT_ID
ENV GCP_LOCATION=$GCP_LOCATION
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_DATABASE_ID=$FIREBASE_DATABASE_ID
ENV GCS_MANGA_BUCKET=$GCS_MANGA_BUCKET
ENV GCS_SIGNED_URL_TTL_MINUTES=$GCS_SIGNED_URL_TTL_MINUTES
ENV CLOUD_TASKS_QUEUE=$CLOUD_TASKS_QUEUE
ENV CLOUD_TASKS_LOCATION=$CLOUD_TASKS_LOCATION
ENV CLOUD_RUN_SERVICE_ACCOUNT=$CLOUD_RUN_SERVICE_ACCOUNT
ENV MANGA_WORKER_URL=$MANGA_WORKER_URL

COPY package*.json ./
RUN npm ci
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080

# 本番依存関係をインストール
COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 8080
CMD ["node", "server.js"]
