# Cloud Build 設定ファイル（Worker サービス: komanavi-worker）
# dev ブランチへの push 時に自動デプロイ

steps:
  # ============================================
  # Step 1: Docker イメージビルド
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/komanavi-worker:${COMMIT_SHA}'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/komanavi-worker:latest'
      - '.'
    dir: 'worker'

  # ============================================
  # Step 2: Artifact Registry へ push
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/komanavi-worker:${COMMIT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/komanavi-worker:latest'

  # ============================================
  # Step 3: Cloud Run デプロイ
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'komanavi-worker'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/komanavi-worker:${COMMIT_SHA}'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '600'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--no-allow-unauthenticated'
      - '--service-account'
      - 'komanavi-cloud-run@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=${PROJECT_ID},GCP_LOCATION=global,FIREBASE_PROJECT_ID=${PROJECT_ID},FIREBASE_DATABASE_ID=komanabi,GCS_MANGA_BUCKET=komanavi-manga-images,GCS_SIGNED_URL_TTL_MINUTES=60'

# ============================================
# イメージを Artifact Registry に登録
# ============================================
images:
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/komanavi-worker:${COMMIT_SHA}'
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/komanavi-worker:latest'

# ============================================
# オプション設定
# ============================================
options:
  # ビルドマシンのスペック
  machineType: 'E2_HIGHCPU_8'
  # ビルドログの保存先
  logging: CLOUD_LOGGING_ONLY
  # タイムアウト
  timeout: '1200s'
